client:
  image: ghcr.io/tim-ings/stremio-web-proxy-client
  host: stremio-web-proxy.tim-ings.com
  port: 3000
  replicas: 1
  tls: true
  ingressAnnotations:
    external-dns.alpha.kubernetes.io/hostname: stremio-web-proxy.tim-ings.com
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-url: http://stremio-web-proxy-oauth2-proxy.stremio-web-proxy.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri

server:
  image: ghcr.io/tim-ings/stremio-web-proxy-server
  host: stremio-web-proxy.tim-ings.com
  port: 3000
  replicas: 1
  tls: true
  ingressAnnotations:
    external-dns.alpha.kubernetes.io/hostname: stremio-web-proxy.tim-ings.com
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-url: http://stremio-web-proxy-oauth2-proxy.stremio-web-proxy.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri

secrets:
- name: stremio-web-proxy.config
  ref: /prod/stremio-web-proxy
  properties:
  - name: config
    key: config
- name: oauth2-proxy
  ref: /prod/infra/oauth2-proxy
  properties:
  - name: client-id
    key: clientId
  - name: client-secret
    key: clientSecret
  - name: cookie-secret
    key: cookieSecret

oauth2-proxy:
  config:
    existingSecret: oauth2-proxy
  
  extraArgs:
    redirect-url: "https://stremio-web-proxy.tim-ings.com/oauth2/callback"

  ingress:
    enabled: true
    path: /oauth2
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: stremio-web-proxy.tim-ings.com
    hosts:
      - stremio-web-proxy.tim-ings.com
    tls:
      - hosts:
        - stremio-web-proxy.tim-ings.com
        secretName: stremio-web-proxy-client-ingress-tls
