client:
  image: stremio-web-proxy-client
  host: stremio-web-proxy.local
  port: 3000
  replicas: 1
  tls: true

server:
  image: stremio-web-proxy-server
  host: stremio-web-proxy.local
  port: 3000
  replicas: 1
  tls: true

localSecrets:
- name: stremio-web-proxy.config
  properties:
  - name: config
    value:
      addonUrls: []
      trackers: []
