{{- range $i, $secret := .Values.secrets -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "{{ $secret.name }}"
spec:
  backendType: systemManager
  data:
    {{ if $secret.property }}
    - key: "{{ $secret.ref }}"
      name: "{{ $secret.property }}"
    {{ else }}
      {{ range $j, $property := $secret.properties }}
      - key: "{{ $secret.ref }}"
        name: "{{ $property.name }}"
        property: "{{ $property.key }}"
      {{ end }}
    {{ end }}
---
{{- end }}
{{- range $i, $secret := .Values.localSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $secret.name }}"
type: Opaque
data:
  {{ range $j, $property := $secret.properties }}
  {{ $property.name }}: {{ $property.value | toJson | b64enc | quote }}
  {{ end }}
---
{{- end }}
