name: Build

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build-server:
    name: Build Server
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: false

  build-client:
    name: Build Client
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          push: false
