name: Test

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test-server:
    name: Test Server
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./server
        run: yarn install --frozen-lockfile
      - name: Run Tests
        working-directory: ./server
        run: yarn test --all

  test-client:
    name: Test Client
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./server
        run: yarn install --frozen-lockfile
      - name: Run Tests
        working-directory: ./server
        run: yarn test --all
